# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CancerInterface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(960, 677)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(301, 9, 0, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(118, 156))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("images/26-clipart-breast-cancer-ribbon-free-cliparts-that-you-can-download-to-PhT6wC-clipart.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(9, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Namelbl = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("OpenSymbol"))
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.Namelbl.setFont(font)
        self.Namelbl.setStyleSheet(_fromUtf8(""))
        self.Namelbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Namelbl.setWordWrap(False)
        self.Namelbl.setObjectName(_fromUtf8("Namelbl"))
        self.horizontalLayout.addWidget(self.Namelbl)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 34, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet(_fromUtf8(""))
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.login_pg = QtGui.QWidget()
        self.login_pg.setStyleSheet(_fromUtf8(""))
        self.login_pg.setObjectName(_fromUtf8("login_pg"))
        self.gridLayout = QtGui.QGridLayout(self.login_pg)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.loginGB = QtGui.QGroupBox(self.login_pg)
        self.loginGB.setEnabled(True)
        self.loginGB.setMaximumSize(QtCore.QSize(111111, 1111111))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.loginGB.setFont(font)
        self.loginGB.setFocusPolicy(QtCore.Qt.NoFocus)
        self.loginGB.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.loginGB.setAcceptDrops(True)
        self.loginGB.setAutoFillBackground(False)
        self.loginGB.setStyleSheet(_fromUtf8(""))
        self.loginGB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.loginGB.setFlat(False)
        self.loginGB.setCheckable(False)
        self.loginGB.setObjectName(_fromUtf8("loginGB"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.loginGB)
        self.verticalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.userlbl = QtGui.QLabel(self.loginGB)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.userlbl.setFont(font)
        self.userlbl.setStyleSheet(_fromUtf8(""))
        self.userlbl.setObjectName(_fromUtf8("userlbl"))
        self.horizontalLayout_3.addWidget(self.userlbl)
        self.usertxt = QtGui.QLineEdit(self.loginGB)
        self.usertxt.setMinimumSize(QtCore.QSize(180, 0))
        self.usertxt.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usertxt.setFont(font)
        self.usertxt.setStyleSheet(_fromUtf8(""))
        self.usertxt.setMaxLength(20)
        self.usertxt.setObjectName(_fromUtf8("usertxt"))
        self.horizontalLayout_3.addWidget(self.usertxt)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.passlbl = QtGui.QLabel(self.loginGB)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.passlbl.setFont(font)
        self.passlbl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passlbl.setIndent(3)
        self.passlbl.setObjectName(_fromUtf8("passlbl"))
        self.horizontalLayout_4.addWidget(self.passlbl)
        self.passtxt = QtGui.QLineEdit(self.loginGB)
        self.passtxt.setMinimumSize(QtCore.QSize(180, 0))
        self.passtxt.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passtxt.setFont(font)
        self.passtxt.setStatusTip(_fromUtf8(""))
        self.passtxt.setAccessibleDescription(_fromUtf8(""))
        self.passtxt.setStyleSheet(_fromUtf8(""))
        self.passtxt.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.passtxt.setInputMask(_fromUtf8(""))
        self.passtxt.setText(_fromUtf8(""))
        self.passtxt.setMaxLength(20)
        self.passtxt.setEchoMode(QtGui.QLineEdit.Password)
        self.passtxt.setObjectName(_fromUtf8("passtxt"))
        self.horizontalLayout_4.addWidget(self.passtxt)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.in_btn = QtGui.QPushButton(self.loginGB)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.in_btn.setFont(font)
        self.in_btn.setObjectName(_fromUtf8("in_btn"))
        self.horizontalLayout_5.addWidget(self.in_btn)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addWidget(self.loginGB)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 4)
        self.horizontalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(2, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.login_pg)
        self.infoPage = QtGui.QWidget()
        self.infoPage.setStyleSheet(_fromUtf8(""))
        self.infoPage.setObjectName(_fromUtf8("infoPage"))
        self.gridLayout_3 = QtGui.QGridLayout(self.infoPage)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.info_gBox = QtGui.QGroupBox(self.infoPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_gBox.sizePolicy().hasHeightForWidth())
        self.info_gBox.setSizePolicy(sizePolicy)
        self.info_gBox.setMaximumSize(QtCore.QSize(840, 1111111))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.info_gBox.setFont(font)
        self.info_gBox.setStyleSheet(_fromUtf8(""))
        self.info_gBox.setObjectName(_fromUtf8("info_gBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.info_gBox)
        self.verticalLayout_4.setContentsMargins(-1, 40, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(20, -1, 20, 3)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.smooth_lbl = QtGui.QLabel(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.smooth_lbl.setFont(font)
        self.smooth_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.smooth_lbl.setIndent(-12)
        self.smooth_lbl.setObjectName(_fromUtf8("smooth_lbl"))
        self.gridLayout_2.addWidget(self.smooth_lbl, 4, 1, 1, 1)
        self.area_txt = QtGui.QLineEdit(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.area_txt.setFont(font)
        self.area_txt.setInputMask(_fromUtf8(""))
        self.area_txt.setMaxLength(32767)
        self.area_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.area_txt.setObjectName(_fromUtf8("area_txt"))
        self.gridLayout_2.addWidget(self.area_txt, 3, 2, 1, 1)
        self.perim_lbl = QtGui.QLabel(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.perim_lbl.setFont(font)
        self.perim_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.perim_lbl.setIndent(-11)
        self.perim_lbl.setObjectName(_fromUtf8("perim_lbl"))
        self.gridLayout_2.addWidget(self.perim_lbl, 2, 1, 1, 1)
        self.smooth_txt = QtGui.QLineEdit(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.smooth_txt.setFont(font)
        self.smooth_txt.setInputMask(_fromUtf8(""))
        self.smooth_txt.setMaxLength(32767)
        self.smooth_txt.setObjectName(_fromUtf8("smooth_txt"))
        self.gridLayout_2.addWidget(self.smooth_txt, 4, 2, 1, 1)
        self.perim_txt = QtGui.QLineEdit(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.perim_txt.setFont(font)
        self.perim_txt.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.perim_txt.setInputMask(_fromUtf8(""))
        self.perim_txt.setMaxLength(32767)
        self.perim_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.perim_txt.setObjectName(_fromUtf8("perim_txt"))
        self.gridLayout_2.addWidget(self.perim_txt, 2, 2, 1, 1)
        self.text_txt = QtGui.QLineEdit(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.text_txt.setFont(font)
        self.text_txt.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.text_txt.setInputMask(_fromUtf8(""))
        self.text_txt.setMaxLength(32767)
        self.text_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.text_txt.setObjectName(_fromUtf8("text_txt"))
        self.gridLayout_2.addWidget(self.text_txt, 1, 2, 1, 1)
        self.radius_txt = QtGui.QLineEdit(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.radius_txt.setFont(font)
        self.radius_txt.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.radius_txt.setInputMask(_fromUtf8(""))
        self.radius_txt.setMaxLength(32767)
        self.radius_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.radius_txt.setObjectName(_fromUtf8("radius_txt"))
        self.gridLayout_2.addWidget(self.radius_txt, 0, 2, 1, 1)
        self.area_lbl = QtGui.QLabel(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.area_lbl.setFont(font)
        self.area_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.area_lbl.setIndent(-11)
        self.area_lbl.setObjectName(_fromUtf8("area_lbl"))
        self.gridLayout_2.addWidget(self.area_lbl, 3, 1, 1, 1)
        self.radius_lbl = QtGui.QLabel(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radius_lbl.setFont(font)
        self.radius_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.radius_lbl.setIndent(-11)
        self.radius_lbl.setObjectName(_fromUtf8("radius_lbl"))
        self.gridLayout_2.addWidget(self.radius_lbl, 0, 1, 1, 1)
        self.text_lbl = QtGui.QLabel(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.text_lbl.setFont(font)
        self.text_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.text_lbl.setIndent(-11)
        self.text_lbl.setObjectName(_fromUtf8("text_lbl"))
        self.gridLayout_2.addWidget(self.text_lbl, 1, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 0, 3, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.compac_txt = QtGui.QLineEdit(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.compac_txt.setFont(font)
        self.compac_txt.setMaxLength(10)
        self.compac_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.compac_txt.setObjectName(_fromUtf8("compac_txt"))
        self.gridLayout_4.addWidget(self.compac_txt, 0, 1, 1, 1)
        self.concv_txt = QtGui.QLineEdit(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.concv_txt.setFont(font)
        self.concv_txt.setMaxLength(10)
        self.concv_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.concv_txt.setObjectName(_fromUtf8("concv_txt"))
        self.gridLayout_4.addWidget(self.concv_txt, 1, 1, 1, 1)
        self.conPoi_lbl = QtGui.QLabel(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.conPoi_lbl.setFont(font)
        self.conPoi_lbl.setStyleSheet(_fromUtf8(""))
        self.conPoi_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.conPoi_lbl.setIndent(-11)
        self.conPoi_lbl.setObjectName(_fromUtf8("conPoi_lbl"))
        self.gridLayout_4.addWidget(self.conPoi_lbl, 2, 0, 1, 1)
        self.conPoi_txt = QtGui.QLineEdit(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.conPoi_txt.setFont(font)
        self.conPoi_txt.setMaxLength(10)
        self.conPoi_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.conPoi_txt.setObjectName(_fromUtf8("conPoi_txt"))
        self.gridLayout_4.addWidget(self.conPoi_txt, 2, 1, 1, 1)
        self.symmetry_ttxt = QtGui.QLineEdit(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.symmetry_ttxt.setFont(font)
        self.symmetry_ttxt.setMaxLength(10)
        self.symmetry_ttxt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.symmetry_ttxt.setObjectName(_fromUtf8("symmetry_ttxt"))
        self.gridLayout_4.addWidget(self.symmetry_ttxt, 3, 1, 1, 1)
        self.frac_lbl = QtGui.QLabel(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.frac_lbl.setFont(font)
        self.frac_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frac_lbl.setIndent(-12)
        self.frac_lbl.setObjectName(_fromUtf8("frac_lbl"))
        self.gridLayout_4.addWidget(self.frac_lbl, 4, 0, 1, 1)
        self.frac_txt = QtGui.QLineEdit(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.frac_txt.setFont(font)
        self.frac_txt.setMaxLength(10)
        self.frac_txt.setObjectName(_fromUtf8("frac_txt"))
        self.gridLayout_4.addWidget(self.frac_txt, 4, 1, 1, 1)
        self.symmetry_lbl = QtGui.QLabel(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.symmetry_lbl.setFont(font)
        self.symmetry_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.symmetry_lbl.setIndent(-11)
        self.symmetry_lbl.setObjectName(_fromUtf8("symmetry_lbl"))
        self.gridLayout_4.addWidget(self.symmetry_lbl, 3, 0, 1, 1)
        self.compac_lbl = QtGui.QLabel(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.compac_lbl.setFont(font)
        self.compac_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.compac_lbl.setIndent(-11)
        self.compac_lbl.setObjectName(_fromUtf8("compac_lbl"))
        self.gridLayout_4.addWidget(self.compac_lbl, 0, 0, 1, 1)
        self.concv_lbl = QtGui.QLabel(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.concv_lbl.setFont(font)
        self.concv_lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.concv_lbl.setIndent(-11)
        self.concv_lbl.setObjectName(_fromUtf8("concv_lbl"))
        self.gridLayout_4.addWidget(self.concv_lbl, 1, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem13 = QtGui.QSpacerItem(20, 14, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem13)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem14)
        self.result_btn = QtGui.QPushButton(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.result_btn.setFont(font)
        self.result_btn.setObjectName(_fromUtf8("result_btn"))
        self.horizontalLayout_16.addWidget(self.result_btn)
        spacerItem15 = QtGui.QSpacerItem(26, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem15)
        self.reset_btn = QtGui.QPushButton(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.reset_btn.setFont(font)
        self.reset_btn.setObjectName(_fromUtf8("reset_btn"))
        self.horizontalLayout_16.addWidget(self.reset_btn)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem16)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem17, 1, 2, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem18, 1, 0, 1, 1)
        self.result_lbl = QtGui.QLabel(self.info_gBox)
        self.result_lbl.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.result_lbl.setFont(font)
        self.result_lbl.setStyleSheet(_fromUtf8(""))
        self.result_lbl.setFrameShape(QtGui.QFrame.Panel)
        self.result_lbl.setFrameShadow(QtGui.QFrame.Plain)
        self.result_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.result_lbl.setWordWrap(False)
        self.result_lbl.setObjectName(_fromUtf8("result_lbl"))
        self.gridLayout_6.addWidget(self.result_lbl, 1, 1, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 7, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem19, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.out_btn = QtGui.QPushButton(self.info_gBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.out_btn.setFont(font)
        self.out_btn.setObjectName(_fromUtf8("out_btn"))
        self.horizontalLayout_7.addWidget(self.out_btn)
        spacerItem21 = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem21)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        spacerItem22 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem22)
        self.gridLayout_3.addWidget(self.info_gBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.infoPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem23)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.passtxt, self.area_txt)
        MainWindow.setTabOrder(self.area_txt, self.smooth_txt)
        MainWindow.setTabOrder(self.smooth_txt, self.usertxt)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BCP", None))
        self.Namelbl.setText(_translate("MainWindow", "Breast Cancer Prediction", None))
        self.loginGB.setTitle(_translate("MainWindow", "Login", None))
        self.userlbl.setText(_translate("MainWindow", "Username:", None))
        self.usertxt.setPlaceholderText(_translate("MainWindow", "Enter Username", None))
        self.passlbl.setText(_translate("MainWindow", "Password:", None))
        self.passtxt.setPlaceholderText(_translate("MainWindow", "Enter Password", None))
        self.in_btn.setText(_translate("MainWindow", "Login", None))
        self.info_gBox.setTitle(_translate("MainWindow", "Patient Information", None))
        self.smooth_lbl.setText(_translate("MainWindow", "Smoothness:", None))
        self.area_txt.setPlaceholderText(_translate("MainWindow", "Enter Number", None))
        self.perim_lbl.setText(_translate("MainWindow", "Perimeter:", None))
        self.smooth_txt.setPlaceholderText(_translate("MainWindow", "Enter Number", None))
        self.perim_txt.setPlaceholderText(_translate("MainWindow", "Enter Number", None))
        self.text_txt.setPlaceholderText(_translate("MainWindow", "Enter Number", None))
        self.radius_txt.setPlaceholderText(_translate("MainWindow", "Enter Number", None))
        self.area_lbl.setText(_translate("MainWindow", "Area:", None))
        self.radius_lbl.setText(_translate("MainWindow", "Raduis:", None))
        self.text_lbl.setText(_translate("MainWindow", "Texture:", None))
        self.compac_txt.setPlaceholderText(_translate("MainWindow", "Enter Number", None))
        self.concv_txt.setPlaceholderText(_translate("MainWindow", "Enter Number", None))
        self.conPoi_lbl.setText(_translate("MainWindow", "Concave Points:", None))
        self.conPoi_txt.setPlaceholderText(_translate("MainWindow", "Enter Number", None))
        self.symmetry_ttxt.setPlaceholderText(_translate("MainWindow", "Enter Number", None))
        self.frac_lbl.setText(_translate("MainWindow", "Fractal Dimension:", None))
        self.frac_txt.setPlaceholderText(_translate("MainWindow", "Enter Number", None))
        self.symmetry_lbl.setText(_translate("MainWindow", "Symmetry:", None))
        self.compac_lbl.setText(_translate("MainWindow", "Compactness:", None))
        self.concv_lbl.setText(_translate("MainWindow", "Concavity:", None))
        self.result_btn.setText(_translate("MainWindow", "Result", None))
        self.reset_btn.setText(_translate("MainWindow", "Reset", None))
        self.result_lbl.setText(_translate("MainWindow", "Result appears here..", None))
        self.out_btn.setText(_translate("MainWindow", "Logout", None))
